kind: Service
apiVersion: v1
metadata:
  name: mariadb
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306
      
---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: mariadb
  labels:
    kubernetes.io/service-name: mariadb
addressType: IPv4
ports:
  - name: tcp
    protocol: TCP
    port: 3306
endpoints:
  - addresses:
      - "192.168.1.122"
    conditions:
      ready: true