kind: Service
apiVersion: v1
metadata:
  name: slurm-mariadb
spec:
  ports:
    - name: mariadb
      protocol: TCP
      port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Endpoints
metadata:
  name: slurm-mariadb
subsets:
  - addresses:
      - ip: 192.168.1.122
    ports:
      - name: mariadb
        port: 3306