apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.serviceName }}
spec:
  selector:
    app: {{ .Values.server.appName }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.server.port }}
    targetPort: {{ .Values.server.port }}
  type: ClusterIP
