nameOverride: ""
fullnameOverride: ""

connect:
  replicaCount: 1
  imagePullSecrets: [ ]

  image:
    repository: quay.io/debezium/connect
    pullPolicy: Always
    tag: "1.9"

  service:
    type: LoadBalancer
    port: 8083
    protocol: TCP
    name: http

  ingress:
    enabled: false

  autoscaling:
    enabled: false

  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 1000m
      memory: 1Gi

  env:
    - name: BOOTSTRAP_SERVERS
      value: "PLAINTEXT:/ha-kafka-controller-headless.kafka:9092"
    - name: GROUP_ID
      value: "1"
    - name: CONFIG_STORAGE_TOPIC
      value: debezium_connect_configs
    - name: OFFSET_STORAGE_TOPIC
      value: debezium_connect_offsets
    - name: STATUS_STORAGE_TOPIC
      value: debezium_connect_statuses

ui:
  enabled: true
  replicaCount: 1
  imagePullSecrets: [ ]

  image:
    repository: debezium/debezium-ui
    pullPolicy: Always
    tag: "1.9"

  service:
    type: LoadBalancer
    port: 8080
    protocol: TCP
    name: http

  ingress:
    enabled: false
    router: private
    host: DEBEZIUM_UI_HOST_ADDRESS

  autoscaling:
    enabled: false

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi

  env:
    - name: KAFKA_CONNECT_URIS
      value: "http://ha-connector-debezium-connect.kafka:8083"

